import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import { QueryProvider } from "@/lib/providers/QueryProvider";
import { Merriweather } from "next/font/google";
import "./globals.css";
import { LayoutWrapper } from "@/components/LayoutWrapper";
import { ThemeProvider } from "@/components/theme-provider";
import { UserProvider } from "@/components/UserProvider";

// Font Merriweather cho heading - "Giọng triết lý"
const merriweather = Merriweather({
  weight: ["700", "900"],
  subsets: ["latin", "vietnamese"],
  variable: "--font-merriweather",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={merriweather.variable}>
      <body className="antialiased bg-background text-foreground">
        <QueryProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <UserProvider>
              <LayoutWrapper>{children}</LayoutWrapper>
            </UserProvider>
          </ThemeProvider>
        </QueryProvider>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
